Parameters:
  PipelineName:
    Default: "nradio-recorder"
    Description: "Name of Codepipeline"
    Type: String
  ImageRepositoryName:
    Default: "nradio-recorder"
    Description: "Name of ECR"
    Type: String
  RepoOwner:
    Default: "kter"
    Description: "Name of Codepipeline"
    Type: String
  GitHubRepo:
    Default: "nradio-recorder"
    Description: "Name of Codepipeline"
    Type: String
  GitHubTokenCodePipeline:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "github_token_codepipeline"
  EmailAddress:
    Description: Email Address
    Type: String
    Default: "me@kter.jp"
Resources:
  ImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ImageRepositoryName
  ArtifactStoreS3:
    Type: 'AWS::S3::Bucket'
  CodePipelineRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "forcodepipeline"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3', '/*']]
                Action:
                  - "s3:*"
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
              - Sid: CodeBuildAccess
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !GetAtt BuildProject.Arn
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
              - 
                Effect: "Allow"
                Resource: !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                Action:
                  - "s3:PutObject"
              - 
                Effect: "Allow"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3', '/*']]
                Action:
                  - "s3:*"
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource:
                  - '*'
              - Sid: ECRAccess2
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                Resource:
                  - 'arn:aws:ecr:*:*:repository/nradio-recorder'
                  #- ''
                  #- - 'arn:aws:ecr:*:*:repository/'
                  #  - !Ref ImageRepositoryName
              - Sid: ECSAccess
                Effect: Allow
                Action:
                  - ecs:*
                Resource:
                  - "*"
              - Sid: KMSParameter
                Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STG_BUCKET
  BuildProject:
    Description: Creating AWS CodeBuild project
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Join [ "/", [ !Ref ArtifactStoreS3, buildcache ]]
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: Branch
            Value: master
        Image: "aws/codebuild/docker:17.09.0"
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Name: ImageBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5
  AppPipeline: 
    Type: "AWS::CodePipeline::Pipeline"
    Properties: 
      Name: !Ref PipelineName
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages: 
        - 
          Name: Source
          Actions: 
            - 
              Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - 
                  Name: SourceOutput
              Configuration: 
                Owner: !Ref RepoOwner
                Repo: !Ref GitHubRepo
                Branch: master
                OAuthToken: !Ref GitHubTokenCodePipeline
              RunOrder: 1
        -
          Name: build
          Actions: 
            - 
              Name: BetaAction
              InputArtifacts: 
                - 
                  Name: SourceOutput
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref BuildProject
              RunOrder: 1
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactStoreS3
      DisableInboundStageTransitions: 
        - 
          StageName: Release
          Reason: "Disabling the transition until integration tests are completed"
