# TODO: Nested Stack https://maya2250.hatenablog.com/entry/2018/06/23/231826
Parameters:
  PipelineName:
    Default: "nradio-recorder"
    Description: "Name of Codepipeline"
    Type: String
  WebImageRepositoryName:
    Default: "web"
    Description: "Name of ECR"
    Type: String
  RepoOwner:
    Default: "kter"
    Description: "Name of Codepipeline"
    Type: String
  WebGitHubRepo:
    Default: "learning_of_codepipeline_ecs_web"
    Description: "Name of Codepipeline"
    Type: String
  GitHubTokenCodePipeline:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "github_token_codepipeline"
  EmailAddress:
    Description: Email Address
    Type: String
    Default: "me@kter.jp"
  DesiredCount:
    Description: ECS desired count
    Type: Number
    Default: 0
  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SourceSecurityGroup
          Subnets: !Ref Subnets
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-app-web
      Memory: 512
      Cpu: 256
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: web
          Image: 848738341109.dkr.ecr.us-east-1.amazonaws.com/web:latest
          Essential: true
          Memory: 256
          PortMappings:
            - ContainerPort: 80
  WebImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref WebImageRepositoryName
  ArtifactStoreS3:
    Type: 'AWS::S3::Bucket'
  CodePipelineRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "forcodepipeline"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3', '/*']]
                Action:
                  - "s3:*"
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
              - Sid: CodeBuildAccess
                Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !GetAtt WebBuildProject.Arn
              - Sid: ECSAccess
                Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:DescribeTasks
                  - ecs:ListTasks
                  - ecs:RegisterTaskDefinition
                  - ecs:UpdateService
                Resource:
                  - "*"
        - PolicyName: PassRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: '*'
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
              - 
                Effect: "Allow"
                Resource: !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                Action:
                  - "s3:PutObject"
              - 
                Effect: "Allow"
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3']]
                  - !Join ['', ['arn:aws:s3:::', !Ref 'ArtifactStoreS3', '/*']]
                Action:
                  - "s3:*"
              - 
                Effect: "Allow"
                Resource: "*"
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:SetRepositoryPolicy
                  - ecr:GetRepositoryPolicy
                Resource:
                  - '*'
              - Sid: ECRAccess2
                Effect: Allow
                Action:
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                Resource:
                  - 'arn:aws:ecr:*:*:repository/web'
                  #- ''
                  #- - 'arn:aws:ecr:*:*:repository/'
                  #  - !Ref ImageRepositoryName
              - Sid: ECSAccess
                Effect: Allow
                Action:
                  - ecs:*
                Resource:
                  - "*"
  WebBuildProject:
    Description: Creating AWS CodeBuild project
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Join [ "/", [ !Ref ArtifactStoreS3, buildcache ]]
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: Branch
            Value: master
        Image: "aws/codebuild/docker:17.09.0"
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      Name: WebImageBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec_web.yml
      TimeoutInMinutes: 5
  AppPipeline: 
    Type: "AWS::CodePipeline::Pipeline"
    Properties: 
      Name: !Ref PipelineName
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages: 
        - 
          Name: Source
          Actions: 
            - 
              Name: WebSourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - 
                  Name: WebSourceOutput
              Configuration: 
                Owner: !Ref RepoOwner
                Repo: !Ref WebGitHubRepo
                Branch: master
                OAuthToken: !Ref GitHubTokenCodePipeline
              RunOrder: 1
        -
          Name: build
          Actions: 
            - 
              Name: web
              InputArtifacts: 
                - 
                  Name: WebSourceOutput
              OutputArtifacts: 
                - 
                  Name: WebBuildOutput
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration: 
                ProjectName: !Ref WebBuildProject
              RunOrder: 1
            - 
        -
          Name: deploy
          Actions: 
            - 
              Name: DeployWebToECS
              InputArtifacts: 
                - 
                  Name: WebBuildOutput
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ECS
              Configuration:
                ClusterName: !Ref ECSCluster
                ServiceName: !Ref ECSService
                FileName: webimagedefinitions.json
              RunOrder: 1
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactStoreS3
